name: Deploy

on:
  push:
    branches: [main]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Cache Composer dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: /tmp/composer-cache
  #         key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

  #     - uses: php-actions/composer@v6

  #     - name: 'Checks'
  #       run: composer check

  build:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          dev: no

      - name: Create dist folder
        run: |
          mkdir -p ./dist && cp -r src public vendor docs dist
          ls dist

      - name: Simple FTP deploy
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          localDir: ./dist
          remoteDir: /api/v1
