name: Deploy

on:
  push:
    branches: [main]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Cache Composer dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: /tmp/composer-cache
  #         key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

  #     - uses: php-actions/composer@v6

  #     - name: 'Checks'
  #       run: composer check

  build:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          dev: yes

      - name: create docs
        run: |
          composer docs

      - name: Create dist folder
        run: |
          mkdir -p ./dist && cp -r src public vendor docs dist
          ls dist

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via lftp
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PWD }}
          LOCAL_DIR: ./dist
          FTP_DESTINATION: /api/v1
        run: |
          echo "Deploying from $LOCAL_DIR to ftp://$FTP_HOST$FTP_DESTINATION"
          lftp $FTP_HOST -u $FTP_USERNAME,$FTP_PASSWORD -e "\
            set ftp:ssl-force false; \
            set ssl:verify-certificate false; \
            mirror --reverse --continue --dereference --verbose $LOCAL_DIR $FTP_DESTINATION; \
            quit"
